from pprint import pformat
from six import iteritems


class LiveVideosList(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, live_videos=None):
        """
        LivePhotosList - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'live_videos': 'list[LiveVideo]'
        }

        self.attribute_map = {
            'live_videos': 'live_videos'
        }

        self._live_videos = live_videos


    @property
    def live_videos(self):
        """
        Gets the live_videos of this LivePhotosList.


        :return: The live_videos of this LivePhotosList.
        :rtype: list[LivePhoto]
        """
        return self._live_videos

    @live_videos.setter
    def live_videos(self, live_videos):
        """
        Sets the live_videos of this LivePhotosList.


        :param live_videos: The live_photos of this LivePhotosList.
        :type: list[LivePhoto]
        """

        self._live_videos = live_videos

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
