# coding: utf-8

"""
    Onfido API

    The Onfido API is used to submit check requests.

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class ReportTypeGroup(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, name=None, group_only=None, report_types=None):
        """
        ReportTypeGroup - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'name': 'str',
            'group_only': 'bool',
            'report_types': 'list[ReportType]'
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'group_only': 'group_only',
            'report_types': 'report_types'
        }

        self._id = id
        self._name = name
        self._group_only = group_only
        self._report_types = report_types


    @property
    def id(self):
        """
        Gets the id of this ReportTypeGroup.


        :return: The id of this ReportTypeGroup.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ReportTypeGroup.


        :param id: The id of this ReportTypeGroup.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this ReportTypeGroup.


        :return: The name of this ReportTypeGroup.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ReportTypeGroup.


        :param name: The name of this ReportTypeGroup.
        :type: str
        """

        self._name = name

    @property
    def group_only(self):
        """
        Gets the group_only of this ReportTypeGroup.


        :return: The group_only of this ReportTypeGroup.
        :rtype: bool
        """
        return self._group_only

    @group_only.setter
    def group_only(self, group_only):
        """
        Sets the group_only of this ReportTypeGroup.


        :param group_only: The group_only of this ReportTypeGroup.
        :type: bool
        """

        self._group_only = group_only

    @property
    def report_types(self):
        """
        Gets the report_types of this ReportTypeGroup.


        :return: The report_types of this ReportTypeGroup.
        :rtype: list[ReportType]
        """
        return self._report_types

    @report_types.setter
    def report_types(self, report_types):
        """
        Sets the report_types of this ReportTypeGroup.


        :param report_types: The report_types of this ReportTypeGroup.
        :type: list[ReportType]
        """

        self._report_types = report_types

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
