# coding: utf-8

"""
    Onfido API

    The Onfido API is used to submit check requests.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ReportType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'variant': 'str',
        'options': 'list[ReportOption]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'variant': 'variant',
        'options': 'options'
    }

    def __init__(self, id=None, name=None, variant=None, options=None):  # noqa: E501
        """ReportType - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._name = None
        self._variant = None
        self._options = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if variant is not None:
            self.variant = variant
        if options is not None:
            self.options = options

    @property
    def id(self):
        """Gets the id of this ReportType.  # noqa: E501


        :return: The id of this ReportType.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ReportType.


        :param id: The id of this ReportType.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ReportType.  # noqa: E501


        :return: The name of this ReportType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ReportType.


        :param name: The name of this ReportType.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def variant(self):
        """Gets the variant of this ReportType.  # noqa: E501


        :return: The variant of this ReportType.  # noqa: E501
        :rtype: str
        """
        return self._variant

    @variant.setter
    def variant(self, variant):
        """Sets the variant of this ReportType.


        :param variant: The variant of this ReportType.  # noqa: E501
        :type: str
        """

        self._variant = variant

    @property
    def options(self):
        """Gets the options of this ReportType.  # noqa: E501


        :return: The options of this ReportType.  # noqa: E501
        :rtype: list[ReportOption]
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this ReportType.


        :param options: The options of this ReportType.  # noqa: E501
        :type: list[ReportOption]
        """

        self._options = options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
