# coding: utf-8

"""
    Onfido API

    The Onfido API is used to submit check requests.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import onfido
from onfido.models.document import Document  # noqa: E501
from onfido.rest import ApiException


class TestDocument(unittest.TestCase):
    """Document unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocument(self):
        """Test Document"""
        # FIXME: construct object with mandatory attributes with example values
        # model = onfido.models.document.Document()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
