# coding: utf-8

"""
    Onfido API

    The Onfido API is used to submit check requests.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import onfido
from onfido.models.sdk_token_response import SdkTokenResponse  # noqa: E501
from onfido.rest import ApiException


class TestSdkTokenResponse(unittest.TestCase):
    """SdkTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSdkTokenResponse(self):
        """Test SdkTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = onfido.models.sdk_token_response.SdkTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
