# coding: utf-8

"""
    Onfido API

    The Onfido API is used to submit check requests.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import onfido
from onfido.models.error_properties import ErrorProperties  # noqa: E501
from onfido.rest import ApiException


class TestErrorProperties(unittest.TestCase):
    """ErrorProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorProperties(self):
        """Test ErrorProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = onfido.models.error_properties.ErrorProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
