# coding: utf-8

"""
    Onfido API

    The Onfido API is used to submit check requests.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import onfido
from onfido.models.addresses_list import AddressesList  # noqa: E501
from onfido.rest import ApiException


class TestAddressesList(unittest.TestCase):
    """AddressesList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressesList(self):
        """Test AddressesList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = onfido.models.addresses_list.AddressesList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
