# coding: utf-8

"""
    Onfido API

    The Onfido API is used to submit check requests.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import onfido
from onfido.models.sdk_token import SdkToken  # noqa: E501
from onfido.rest import ApiException


class TestSdkToken(unittest.TestCase):
    """SdkToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSdkToken(self):
        """Test SdkToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = onfido.models.sdk_token.SdkToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
